sudo: required

language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      env: PYTHON=2.7
    - os: linux
      dist: trusty
      env: PYTHON=3.5
    - os: osx
      osx_image: xcode7
      env: PYTHON=2.7
    - os: osx
      osx_image: xcode7
      env: PYTHON=3.5

install:
  - ./.travis/install-dependencies.sh
  - ./.travis/install-ray.sh

  - if [[ "$PYTHON" == "3.5" ]]; then export PATH="$HOME/miniconda/bin:$PATH"; fi

  - cd python/ray/core
  - bash ../../../src/common/test/run_tests.sh
  - bash ../../../src/plasma/test/run_tests.sh
  - bash ../../../src/local_scheduler/test/run_tests.sh
  - cd ../../..

script:
  - if [[ "$PYTHON" == "3.5" ]]; then export PATH="$HOME/miniconda/bin:$PATH"; fi

  - bash multiple_local_schedulers.sh
